name: user_repository
description: The Repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # equatable: ^2.0.5
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.0.0
  firebase_core: ^3.8.1
  toggle_switch: ^2.3.0
  icons_plus: ^5.0.0
  # firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true